config/routes.rb
Rails.application.routes.draw do
  get 'spotty_api/autocomplete'

  get 'spotty_api/song'

  get 'spotty_api/artist'

  get 'spotty_api/album'

  get 'spotty_api/top_tracks'

  get 'spotty_api/suggest_songs'

  root "application#home"
  devise_for :users
  
  resources :profiles do
    get 'edit_profile' => 'profiles#edit_profile'
    get 'edit_contact' => 'profiles#edit_contact'
    get 'getInstruments' => 'profiles#getInstruments'
    post 'addInstrument' => 'profiles#addInstrument'
    delete 'removeInstrument' => 'profiles#removeInstrument'
  end

  get 'jam_groups/:id/chat' => 'jam_groups#chat', as: 'jam_group_chat' 
  post 'jam_groups/:id/chat' => 'jam_groups#chat', as: 'jam_group_comment' 
  resources :jam_groups
  get 'jam_group_members/list_pending' => 'jam_group_members#list_pending'
  resources :jam_group_members do
    post 'accept_invite' => 'jam_group_members#accept_invite'
    post 'reject_invite' => 'jam_group_members#reject_invite'
  end
  

end

app/models/jam_group.rb
class JamGroup < ApplicationRecord
  has_many :jam_group_members, :dependent => :destroy
  has_many :profiles, through: :jam_group_members
  has_many :comments, :dependent => :destroy
  alias_attribute :members, :profiles

  after_initialize :set_defaults, unless: :persisted?
  # The set_defaults will only work if the object is new

  private

    def set_defaults
      self.name ||= 'Unnamed Group'
      self.image_url ||= '/img/headphone.png'
      self.description ||= 'Insert description here...'
    end
end

app/controllers/jam_groups_controller.rb
class JamGroupsController < ApplicationController
  protect_from_forgery prepend: true
  before_action :set_jam_group, only: [:show, :chat, :edit, :update, :destroy]
  before_action :authenticate_user!
  layout :resolve_layout

  # GET /jam_groups
  # GET /jam_groups.json
  def index
    if params[:all] == 'true'
      @jam_groups = JamGroup.all
    else
      members = JamGroupMember.where(profile: current_user.profile).where(status: :joined).all
      @jam_groups = members.map {|m| m.jam_group}
    end
  end

  # GET /jam_groups/1
  # GET /jam_groups/1.json
  def show
    excluded_profile_ids = @jam_group.members.select(:id)
    @nonmembers = Profile.where.not(id: excluded_profile_ids)
    @nonmembers = @nonmembers.by_name(params[:name]) if params[:name].present?
    @nonmembers = @nonmembers.by_location(params[:location]) if params[:location].present?
    @nonmembers = @nonmembers.first(6)
  end

  def chat
    self.show
    if request.post?
      @comment = @jam_group.comments.new(new_comment_params)
      @comment.profile = current_user.profile
      
      respond_to do |format|
        if @comment.save
          format.html { redirect_to jam_group_chat_path(@jam_group), notice: 'Successfully added comment' }
          format.json { render :chat, status: :created, location: jam_group_chat_path(@jam_group) }
        else
          format.html { redirect_to jam_group_chat_path(@jam_group), alert: 'Failed to add comment' }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    else
      @comment = @jam_group.comments.new
      @comment.profile = current_user.profile
    end
      @comments = @jam_group.comments.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /jam_groups/new
  def new
    @jam_group = JamGroup.new
  end

  # GET /jam_groups/1/edit
  def edit
  end

  # POST /jam_groups
  # POST /jam_groups.json
  def create
    @jam_group = JamGroup.new(jam_group_params)

    respond_to do |format|
      if @jam_group.save
        jgm = JamGroupMember.new(
          profile: current_user.profile, 
          jam_group: @jam_group, 
          invited_by: current_user.profile, 
          status: :joined
        )
        jgm.save
        format.html { redirect_to @jam_group, notice: 'Jam group was successfully created.' }
        format.json { render :show, status: :created, location: @jam_group }
      else
        format.html { render :new }
        format.json { render json: @jam_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jam_groups/1
  # PATCH/PUT /jam_groups/1.json
  def update
    respond_to do |format|
      if @jam_group.update(jam_group_params)
        format.html { redirect_to @jam_group, notice: 'Jam group was successfully updated.' }
        format.json { render :show, status: :ok, location: @jam_group }
      else
        format.html { render :edit }
        format.json { render json: @jam_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jam_groups/1
  # DELETE /jam_groups/1.json
  def destroy
    destroy_group = false
    if params[:force_delete] == 'true'
      destroy_group = true
    end

    profile = current_user.profile
    if profile.jam_groups.all.include?(@jam_group)
      profile.jam_group_member.delete(JamGroupMember.where(profile: profile).where(jam_group: @jam_group).limit(1))
      if @jam_group.members.length == 0
        destroy_group = true
      end
    end

    if destroy_group
      @jam_group.destroy
      respond_to do |format|
        format.html { redirect_to jam_groups_url, notice: 'Jam group was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to jam_groups_url, notice: 'Successfully left the Jam group.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jam_group
      @jam_group = JamGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jam_group_params
      params.require(:jam_group).permit(:name, :image_url, :description)
    end

    def new_comment_params
      params.require(:comment).permit(:title, :comment)
    end

    def resolve_layout
      case action_name
      when "index"
        "jam_groups"
      else
        "application"
      end
    end
end

app/helpers/jam_groups_helper.rb
module JamGroupsHelper
end

app/views/jam_groups/_form.html.erb
<%= form_for(jam_group) do |f| %>
  <% if jam_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(jam_group.errors.count, "error") %> prohibited this jam_group from being saved:</h2>

      <ul>
      <% jam_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image_url %>
    <%= f.text_field :image_url, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control"  %>
  </div>

  <div class="actions">
    <%= f.submit "Save Jam Group", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/jam_groups/_show.html.erb
<div class="container">
  <div class="page-header row">
    <div class="col-md-1 col-sm-2 col-xs-2">
      <img class="media-object responsive-image" src="<%= @jam_group.image_url %>" alt="<%= @jam_group.name %> Image" height="80" width="80">
    </div>
    <div class="col-md-10 col-sm-8 col-xs-8">
      <h1><%= @jam_group.name %></h1>
      <p><small><b>Last Updated:</b> <%= @jam_group.updated_at %></small></p>
    </div>
    
    <% if @jam_group.jam_group_members.find_by(profile_id: current_user.profile.id) %>
      <div class="col-md-1 col-sm-2 col-xs-2">
        <br/>
        <div class="btn-group pull-right">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Actions <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <li><%= link_to 'Edit Group Info', edit_jam_group_path(@jam_group) %></li>
            <li><%= link_to 'Leave this group', @jam_group, method: :delete, data: { confirm: 'Are you sure?' } %></li>
            <li role="separator" class="divider"></li>
            <li class="text-danger"><%= link_to 'Delete this group', jam_group_path(@jam_group, force_delete: 'true'), method: :delete, data: { confirm: 'Are you sure?' }, class: "text-danger" %></li>
          </ul>
        </div>
      </div>
    <% end %>
    
  </div>
  
  <% if @jam_group.jam_group_members.find_by(profile_id: current_user.profile.id) %>
  <div class="row">
      <div class="col-sm-7">
        <ul class="nav nav-tabs">
          <li role="presentation" <% if yield(:page) == 'info' %>class="active"<% end %> ><%= link_to 'Info', @jam_group %></li>
          <li role="presentation" <% if yield(:page) == 'chat' %>class="active"<% end %> ><%= link_to 'Chat', jam_group_chat_url(@jam_group) %></li>
        </ul>
        <%= yield %>
        <hr>
      </div>
      <div class="col-sm-1"></div>
      
      <div class="col-sm-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            Members 
          </div>
  
          <div class="panel-body">
            <div class="row hidden" id="add-member-warning">
              <div class="col-xs-12"><p class="text-danger">* Select a user first!</p></div>
            </div>
            <div class="row">
<!-- Begin add users -->

            <!-- Trigger the modal with a button -->
            <button type="button" class="btn btn-primary btn-lg" style='margin-left: 0.5em;' data-toggle="modal" data-target="#searchModal">Add Members!</button>
            
            <!-- Modal -->
            <div id="searchModal" class="modal fade" role="dialog">
              <div class="modal-dialog">
            
                <!-- Modal content-->
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h3 class="modal-title">Search for Jam Members!</h3>
                  </div>
                  
                  <!-- Begin modal body --> 
                  <div class="modal-body" style='padding: 0'>
                    <%= form_tag(jam_group_path, :method => "get", id: "search-form", style: 'margin: 10px') do %>
                    <%= text_field_tag :name, params[:name], placeholder: "Find by name" %>
                    <%= text_field_tag :location, params[:location], placeholder: "Find by location" %>
                    <%= submit_tag "Go!" %>
                    <% end %>
                    <div class="list-group" style='margin-bottom: 0;'>
                      <% if @nonmembers.each do |profile| %>
                       <div class="list-group-item">
                          <div class="media">
                            <div class="media-left">
                              <%= gravatar_for profile.user, class: "media-object" %>
                            </div>
                            <div class="media-body">
                              <%= link_to profile_path(profile), target: "_blank" do %>
                              <h4 class="media-heading"><%= profile.full_name %></h4>
                              <% end %>
                              <h4 class="media-heading">Location: <%= profile.location %></h4>
                              <h4 class="media-heading">Age: <%= profile.age %></h4>
                            </div>
                            <div class="media-right">
                              <%= button_to "Invite!", { controller: 'jam_group_members', action: 'create'}, remote: true, params: { profile: profile.id, jam_group: @jam_group.id }, class: 'btn btn-primary btn-med'  %>
                            </div>
                          </div>
                        </div>

                      <% end.empty? %>
                        <li> Couldn't find any users!</li>
                      <% end %>
                    </div>
                  </div>
                  <!-- End modal body -->
                  
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  </div>
                </div>
            
              </div>
            </div>

<!-- End add users -->
            </div>
          </div>
  
          <div class="list-group">
            <% if @jam_group.jam_group_members.each do |member| %>
              <%= link_to profile_path(member.profile), class: "list-group-item" do %>
                <div class="media">
                  <div class="media-left">
                    <%= gravatar_for member.profile.user, clazz: "media-object" %>
                  </div>
                  <div class="media-body">
                    <h4 class="media-heading"><%= member.profile.full_name %></h4>
                    <% if member.status.capitalize == "Pending" %>
                      Pending since
                    <% else %>
                      <%= member.status.capitalize %>
                    <% end %> 
                    <%= member.updated_at %>
                    <% if member.status.capitalize == "Joined" %>
                      <b>Email:</b> <%= member.profile.user.email %>
                      <% if !member.profile.phone.blank? %>
                        </br>
                        <b>Phone:</b> <%= member.profile.phone %>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              <% end %>
            <% end.empty? %>
              <li>No Members!</li>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% else %>
    You are not a member of this Jam Group.
  <% end %>
</div>

<script>
function $_GET(param) {
  var vars = {};
  window.location.href.replace( location.hash, '' ).replace( 
    /[?&]+([^=&]+)=?([^&]*)?/gi, // regexp
    function( m, key, value ) { // callback
      vars[key] = value !== undefined ? value : '';
    }
  );

  if ( param ) {
    return vars[param] ? vars[param] : null;  
  }
  return vars;
}

  if ($_GET('location') != null || $_GET('name') != null) {
    console.log(location)
    $('#searchModal').modal('show');
  }
</script>

app/views/jam_groups/chat.html.erb
<% provide(:page, 'chat') %>
<%= render :layout => 'jam_groups/show' do %>
  <br>
  <% if @jam_group.jam_group_members.find_by(profile_id: current_user.profile.id) %>
    <%= form_for @comment, url: {action: "chat"} do |f| %>
      <%= f.text_area :comment, class: "form-control", placeholder: "Comment" %>
      <%= f.submit "Add Comment", class: "btn btn-primary" %>
    <% end %>
    <br>
  
   <%= will_paginate @comments %>
  
    <ul class="media-list">
      <% @comments.order('created_at DESC').each do |comment| %>
        <li class="media">
          <div class="media-left">
            <%= gravatar_for comment.profile.user, "media-object", "64x64" %>
          </div>
          <div class="media-body">
            <h4 class="media-heading"><%= comment.profile.full_name %> <small><%= timeago(comment.created_at) %></small></h4>
            <%= comment.comment %>
          </div>
        </li>
      <% end %>
    </ul>
    
    <%= will_paginate @comments %>
    
  <% else %>
    You are not a member of this Jam Group.
  <% end %>

<% end %>

app/views/jam_groups/edit.html.erb
<div class="container">
  <h1>Editing Jam Group</h1>

  <% if @jam_group.jam_group_members.find_by(profile_id: current_user.profile.id) %>
    <%= render 'form', jam_group: @jam_group %>
    <%= link_to 'Show', @jam_group %> |
  <% else %>
    You are not a member of this Jam Group </br>
  <% end %>
  
  <%= link_to 'Back', jam_groups_path %>
</div>

app/views/jam_groups/index.html.erb
<% provide(:page, 'index') %>
<div class="container">
  <p><%= link_to 'Create a Jam Group', new_jam_group_path %></p>

  <ul class="media-list">
    <% if @jam_groups.each do |jam_group| %>
      <li class="media well">
        <div class="media-left">
          <%= link_to jam_group do %>
            <img class="media-object responsive-image" src="<%= jam_group.image_url %>" alt="<%= jam_group.name %> Image" height="80" width="80">
          <% end %>
        </div>
        <div class="media-body">
          <h4 class="media-heading"><%= link_to jam_group.name, jam_group %></h4>
          <p><%= jam_group.description %></p>
        </div>
      </li>
    <% end.empty? %>
      <h3>Looks like you don't have any jam groups set up yet! Try creating one.</h3>
    <% end %>
  </ul>

</div>

app/views/jam_groups/new.html.erb
<div class="container">
  <h1>New Jam Group</h1>

  <%= render 'form', jam_group: @jam_group %>

  <%= link_to 'Back', jam_groups_path %>
</div>

app/views/jam_groups/show.html.erb
<% provide(:page, 'info') %>
<%= render :layout => 'jam_groups/show' do %>
  <h3>Description:</h3>
  <p><%= @jam_group.description %></p>
<% end %>