config/routes.rb
Rails.application.routes.draw do
  get 'spotty_api/autocomplete'

  get 'spotty_api/song'

  get 'spotty_api/artist'

  get 'spotty_api/album'

  get 'spotty_api/top_tracks'

  get 'spotty_api/suggest_songs'

  root "application#home"
  devise_for :users
  
  resources :profiles do
    get 'edit_profile' => 'profiles#edit_profile'
    get 'edit_contact' => 'profiles#edit_contact'
    get 'getInstruments' => 'profiles#getInstruments'
    post 'addInstrument' => 'profiles#addInstrument'
    delete 'removeInstrument' => 'profiles#removeInstrument'
  end

  get 'jam_groups/:id/chat' => 'jam_groups#chat', as: 'jam_group_chat' 
  post 'jam_groups/:id/chat' => 'jam_groups#chat', as: 'jam_group_comment' 
  resources :jam_groups
  get 'jam_group_members/list_pending' => 'jam_group_members#list_pending'
  resources :jam_group_members do
    post 'accept_invite' => 'jam_group_members#accept_invite'
    post 'reject_invite' => 'jam_group_members#reject_invite'
  end
  

end

app/models/jam_group_member.rb
class JamGroupMember < ApplicationRecord
  enum status: { pending: 0, joined: 1, rejected: 2, left: 3, removed: 4 }
  belongs_to :profile
  belongs_to :jam_group
  belongs_to :invited_by, :class_name => 'Profile', :foreign_key => 'invited_by', validate: true

  before_destroy :destroy_jam_groups

  private

    def destroy_jam_groups
      grp = self.jam_group
      if grp.members.count == 1 and grp.jam_group_members.first == self
        grp.destroy
      end
    end
end

app/controllers/jam_group_members_controller.rb
class JamGroupMembersController < ApplicationController
  before_action :set_jam_group_member, only: [:accept_invite, :reject_invite, :show, :edit, :update, :destroy]
  before_action :authenticate_user!
  layout :resolve_layout

  # GET /jam_group_members
  # GET /jam_group_members.json
  def index
    @jam_group_members = JamGroupMember.all
  end

  def list_pending
    @invites = JamGroupMember.where(profile: current_user.profile).where(status: :pending).all
    render "list_invites"
  end

  def accept_invite
    @jam_group_member.status = :joined 
    @jam_group_member.save

    respond_to do |format|
      format.html { redirect_to jam_group_path(@jam_group_member.jam_group), notice: "Joined Jam Group '#{@jam_group_member.jam_group.name}'" }
      format.json { render status: :ok }
    end
  end

  def reject_invite
    @jam_group_member.status = :rejected 
    @jam_group_member.save

    respond_to do |format|
      format.html { redirect_to jam_group_members_list_pending_path, notice: "Rejected Jam Group invitation for '#{@jam_group_member.jam_group.name}'" }
      format.html { redirect_to jam_group_path(@jam_group_member.jam_group), notice: "Rejected Jam Group invitation for '#{@jam_group_member.jam_group.name}'" }
      format.json { render status: :ok }
    end
  end

  # GET /jam_group_members/1
  # GET /jam_group_members/1.json
  def show
  end

  # GET /jam_group_members/new
  def new
    @jam_group_member = JamGroupMember.new
  end

  # GET /jam_group_members/1/edit
  def edit
  end

  # POST /jam_group_members
  # POST /jam_group_members.json
  def create
    #@jam_group_member = JamGroupMember.new(jam_group_member_params)
    if params[:jam_group] != nil && params[:profile] != nil
      @jam_group_member = JamGroupMember.new(profile_id: params[:profile], jam_group_id: params[:jam_group])
      @jam_group_member.invited_by = current_user.profile

      #if params[:invited_by] != nil
      #  @jam_group_member.invited_by = params[:invited_by]
      #else
      #  @jam_group_member.invited_by = params[:profile]
      #end

      respond_to do |format|
        if @jam_group_member.save
          format.html { redirect_to JamGroup.find(params[:jam_group]), notice: 'Jam group member was successfully invited.' }
          format.json { render :show, status: :created, location: @jam_group_member }
        else
          format.html { redirect_to JamGroup.find(params[:jam_group]) }
          format.json { render json: @jam_group_member.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to jam_groups_url }
        format.json { render json: {error: "Invalid Request"}, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jam_group_members/1
  # PATCH/PUT /jam_group_members/1.json
  def update
    respond_to do |format|
      if @jam_group_member.update(jam_group_member_params)
        format.html { redirect_to @jam_group_member, notice: 'Jam group member was successfully updated.' }
        format.json { render :show, status: :ok, location: @jam_group_member }
      else
        format.html { render :edit }
        format.json { render json: @jam_group_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jam_group_members/1
  # DELETE /jam_group_members/1.json
  def destroy
    @jam_group_member.destroy
    respond_to do |format|
      format.html { redirect_to jam_group_members_url, notice: 'Jam group member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jam_group_member
      if params[:id] != nil
        @jam_group_member = JamGroupMember.find(params[:id])
      elsif params[:jam_group_member_id] != nil
        @jam_group_member = JamGroupMember.find(params[:jam_group_member_id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jam_group_member_params
      params.require(:jam_group_member).permit(:jam_group, :profile, :invited_by)
    end


    def resolve_layout
      case action_name
      when "list_pending"
        "jam_groups"
      else
        "application"
      end
    end
end

app/helpers/jam_group_members_helper.rb
module JamGroupMembersHelper
end

app/views/jam_group_members/_form.html.erb
<%= form_for(jam_group_member) do |f| %>
  <% if jam_group_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(jam_group_member.errors.count, "error") %> prohibited this jam_group_member from being saved:</h2>

      <ul>
      <% jam_group_member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jam_group_members/edit.html.erb
<h1>Editing Jam Group Member</h1>

<%= render 'form', jam_group_member: @jam_group_member %>

<%= link_to 'Show', @jam_group_member %> |
<%= link_to 'Back', jam_group_members_path %>

app/views/jam_group_members/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Jam Group Members</h1>

  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>User</th>
        <th>JamGroup</th>
        <th>Status</th>
        <th>Invited By</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @jam_group_members.each do |jam_group_member| %>
        <tr>
          <td><%= jam_group_member.id %></td>
          <td><%= jam_group_member.profile.display_inline %></td>
          <td><%= jam_group_member.jam_group.name %></td>
          <td><%= jam_group_member.status %></td>
          <td><%= jam_group_member.invited_by.display_inline %></td>
          <td><%= link_to 'Show', jam_group_member %></td>
          <td><%= link_to 'Edit', edit_jam_group_member_path(jam_group_member) %></td>
          <td><%= link_to 'Destroy', jam_group_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Jam Group Member', new_jam_group_member_path %>
</div>

app/views/jam_group_members/list_invites.html.erb
<% provide(:page, 'invitations') %>

<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th>JamGroup</th>
        <th>Status</th>
        <th>Invited By</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @invites.each do |invite| %>
        <tr>
          <td><%= invite.jam_group.name %></td>
          <td><%= invite.status %></td>
          <td><%= invite.invited_by.display_inline %></td>
          <td><%= link_to 'Accept', jam_group_member_accept_invite_path(jam_group_member_id: invite.id), method: :post, class: "text-success" %></td>
          <td><%= link_to 'Reject', jam_group_member_reject_invite_path(jam_group_member_id: invite.id), method: :post, class: "text-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/jam_group_members/new.html.erb
<h1>New Jam Group Member</h1>

<%= render 'form', jam_group_member: @jam_group_member %>

<%= link_to 'Back', jam_group_members_path %>

app/views/jam_group_members/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_jam_group_member_path(@jam_group_member) %> |
<%= link_to 'Back', jam_group_members_path %>