config/routes.rb
Rails.application.routes.draw do
  get 'spotty_api/autocomplete'

  get 'spotty_api/song'

  get 'spotty_api/artist'

  get 'spotty_api/album'

  get 'spotty_api/top_tracks'

  get 'spotty_api/suggest_songs'

  root "application#home"
  devise_for :users
  
  resources :profiles do
    get 'edit_profile' => 'profiles#edit_profile'
    get 'edit_contact' => 'profiles#edit_contact'
    get 'getInstruments' => 'profiles#getInstruments'
    post 'addInstrument' => 'profiles#addInstrument'
    delete 'removeInstrument' => 'profiles#removeInstrument'
  end

  get 'jam_groups/:id/chat' => 'jam_groups#chat', as: 'jam_group_chat' 
  post 'jam_groups/:id/chat' => 'jam_groups#chat', as: 'jam_group_comment' 
  resources :jam_groups
  get 'jam_group_members/list_pending' => 'jam_group_members#list_pending'
  resources :jam_group_members do
    post 'accept_invite' => 'jam_group_members#accept_invite'
    post 'reject_invite' => 'jam_group_members#reject_invite'
  end
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>JamSesh | An Organization Tool for Musicians</title>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render "shared/header" %>

    <div class="body-content">
      <% if flash[:error] or flash[:notice] or flash[:alert] %>
        <div class="container">
          <br/>
          <%= content_tag(:div, flash[:error], :id => "flash_error", :class => "alert alert-error") if flash[:error] %>
          <%= content_tag(:div, flash[:notice], :id => "flash_notice", :class => "alert alert-info") if flash[:notice] %>
          <%= content_tag(:div, flash[:alert], :id => "flash_alert", :class => "alert alert-warning") if flash[:alert] %>
        </div>
      <% end %>

      <%= yield :tabs %>
      <%= yield %>
    </div>

    <%= javascript_tag do %>
       $(function() {
          $("time.timeago").timeago();
       });
    <% end %>
  </body>
</html>

app/views/layouts/jam_groups.html.erb
<% content_for :tabs do -%>
<div class="container">
  <h1 class="title">Jam Groups</h1>
  <br/>
  <ul class="nav nav-tabs nav-justified">
    <li role="presentation" <% if yield(:page) == 'index' %>class="active"<% end %>>
      <%= link_to 'My Jam Groups', jam_groups_url %>
    </li>
    <li role="presentation" <% if yield(:page) == 'invitations' %>class="active"<% end %>>
      <%= link_to 'Jam Invitations', jam_group_members_list_pending_path %>
    </li>
  </ul>
  <br/>
</div>
<% end -%>

<%= render :file => "layouts/application" %>

app/views/layouts/profiles.html.erb
<% content_for :tabs do -%>
<div class="container">
  <h1 class="title">Edit Profile</h1>
  <br/>
  <ul class="nav nav-tabs nav-justified">
    <li role="presentation" <% if yield(:page) == 'edit_profile' %>class="active"<% end %>>
      <%= link_to 'Public Profile', profile_edit_profile_path %>
    </li>
    <li role="presentation" <% if yield(:page) == 'edit_contact' %>class="active"<% end %>>
      <%= link_to 'Contact Info', profile_edit_contact_path %>
    </li>
  </ul>
  <br/>
</div>
<% end -%>

<%= render :file => "layouts/application" %>

app/views/layouts/tabs.html.erb
<% content_for :tabs do -%>
<div class="container">
  <h1 class="title">Insert Title Here</h1>
  <br/>
  <ul class="nav nav-tabs nav-justified">
    <li role="presentation" <% if yield(:page) == 'page1' %>class="active"<% end %>>
      <%= link_to 'Link1', jam_groups_url %>
    </li>
    <li role="presentation" <% if yield(:page) == 'page2' %>class="active"<% end %>>
      <%= link_to 'Link2', jam_groups_url %>
    </li>
    <li role="presentation" <% if yield(:page) == 'page3' %>class="active"<% end %>>
      <%= link_to 'Link3', jam_groups_url %>
    </li>
  </ul>
  <br/>
</div>
<% end -%>

<%= render :file => "layouts/application" %>